version: '3.9'
services: 
  confluent_cost_exporter:
    image: confluent/confluent_cost_exporter
    build:
      context: confluent_cloud_cost_exporter
      dockerfile: ./Dockerfile
    container_name: confluent_cost_exporter
    environment:
    - CONFLUENT_CLOUD_API_KEY=<CLOUD_API_KEY>
    - CONFLUENT_CLOUD_API_SECRET=<CLOUD_API_SECRET>
    - CACHE_EXPIRATION=240m
    - PORT=7979 
    ports:
      - 7979:7979

  prometheus:
    image: prom/prometheus
    hostname: prometheus
    container_name: prometheus
    ports:
    - 9090:9090 
    restart: always
    volumes:
    - ./env/:/etc/prometheus/   
   
  grafana:
    image: grafana/grafana:8.1.3
    hostname: grafana
    container_name: grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel
      GF_SECURITY_ADMIN_USER: "admin"  
      GF_SECURITY_ADMIN_PASSWORD: "1234"
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
    - 3000:3000
    volumes:
    - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on: 
    - prometheus 