version: '3.9'
services:
  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: elasticsearch
    volumes:
      - "./elasticsearch/data:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.8.0
    container_name: metricbeat
    environment:
      HOSTS_ELASTICSEARCH: http://elasticsearch:9200 
      HOSTS_KIBANA: http://kibana:5601
    volumes: 
      - ./env/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro 
    depends_on:
      - elasticsearch
      - kibana
  
  confluent_cost_exporter:
    image: confluent/confluent_cost_exporter
    build:
      context: confluent_cloud_cost_exporter
      dockerfile: ./Dockerfile
    container_name: confluent_cost_exporter
    environment:
    - CONFLUENT_CLOUD_API_KEY=<CONFLUENT_API_KEY>
    - CONFLUENT_CLOUD_API_SECRET=<CONFLUENT_API_SECRET>
    - CACHE_EXPIRATION=240m
    - PORT=7979 
    ports:
      - 7979:7979
 