global:
 scrape_interval:     1m # By default, scrape targets every 15 seconds.
 evaluation_interval: 1m # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: Confluent Cloud
    scrape_interval: 1m
    scrape_timeout: 1m
    honor_timestamps: true
    static_configs:
      - targets:
        - api.telemetry.confluent.cloud
    scheme: https
    basic_auth:
      username: <CONFLUENT_CLOUD_API_KEY>
      password: <CONFLUENT_CLOUD_API_SECRET>
    metrics_path: /v2/metrics/cloud/export
    params:
      resource.kafka.id:
        - lkc-<CLUSTER_ID>
  - job_name: json_exporter
    scrape_interval: 5m
    scrape_timeout: 30s
    honor_labels: true 
    metrics_path: /probe  
    static_configs:
      - targets: 
        - https://api.confluent.cloud/billing/v1/costs
           
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target 
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json_exporter:7979     
      
         
 
 