{
 "title": "Confluent Cloud Cost",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Environment",
    "query": {
     "query": "label_values(confluent_cloud_cost_amount, environment)"
    }
   },
   {
    "name": "Kafka",
    "query": {
     "query": "label_values(confluent_cloud_cost_amount{id=~\"lkc.*\",environment=~\"$Environment\"}, id)"
    }
   },
   {
    "name": "Connectors",
    "query": {
     "query": "label_values(confluent_cloud_cost_amount{id=~\"lcc.*\",environment=~\"$Environment\"}, id)"
    }
   },
   {
    "name": "KSQL",
    "query": {
     "query": "label_values(confluent_cloud_cost_amount{id=~\"lksqlc.*\",environment=~\"$Environment\"}, id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Bill", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Confluent Cloud Total cost",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_cloud_cost_amount{environment=~\"$Environment\"})"
    }
   ]
  },
  {
   "title": "Confluent Kafka Clusters",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_cloud_cost_amount{id=~\"lkc.*\",environment=~\"$Environment\"})"
    }
   ]
  },
  {
   "title": "Confluent Connectors",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_cloud_cost_amount{id=~\"lcc.*\",environment=~\"$Environment\"})"
    }
   ]
  },
  {
   "title": "Schema Registry",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_cloud_cost_amount{id=~\"lsrc.*\", environment=~\"$Environment\"})"
    }
   ]
  },
  {
   "title": "KSQLDB",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (id,resource)(confluent_cloud_cost_amount{id=~\"lksqlc.*\",environment=~\"$Environment\",id=~\"$KSQL\"})"
    }
   ]
  },
  {
   "title": "by Product",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(product)(confluent_cloud_cost_amount{environment=~\"$Environment\"})",
     "legendFormat": "{{ product }}"
    }
   ]
  },
  {
   "title": "By Day",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(end_date)(confluent_cloud_cost_amount{environment=~\"$Environment\"})",
     "legendFormat": "{{end_date}}"
    }
   ]
  },
  { "title": "Cost Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "by Environment",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(environment)(confluent_cloud_cost_amount{environment=~\"$Environment\"})",
     "legendFormat": "{{ environment }}"
    }
   ]
  },
  { "title": "Confluent Kafka ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Kafka Clusters",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(id,resource)(confluent_cloud_cost_amount{id=~\"lkc.*\",environment=~\"$Environment\",id=~\"$Kafka\"})",
     "legendFormat": "{{ id }} - {{ resource }}"
    }
   ]
  },
  { "title": "Confluent Connectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Connectors",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (id,resource)(confluent_cloud_cost_amount{id=~\"lcc.*\",environment=~\"$Environment\",id=~\"$Connectors\"})",
     "legendFormat": "{{ id }} - {{ resource }}"
    }
   ]
  },
  { "title": "KSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "KSQL",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (id,resource)(confluent_cloud_cost_amount{id=~\"lksqlc.*\",environment=~\"$Environment\"})",
     "legendFormat": "{{ id }} - {{ resource }}"
    }
   ]
  },
  {
   "title": "All",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cost by Resource",
     "type": "bargauge",
     "gridPos": { "h": 22, "w": 15, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (id) (confluent_cloud_cost_amount)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  }
 ]
}